version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: wallet_daemon
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger_secret
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -U ledger -d postgres"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-management}
    command: rabbitmq-server
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # RabbitMQ original port (to be accessed from host)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 15s
      retries: 100